version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - ./DOCKER/N8N_DATA:/home/node/.n8n
      - .:/data
    networks:
      - agente-net

  umap-service:
    build:
      context: ./umap_service
    container_name: umap-service
    ports:
      - 8000:8000
    networks:
      - agente-net

  cluster-service:
    build:
      context: ./clustering_service
    container_name: cluster-service
    ports:
      - 8500:8500
    networks:
      - agente-net

  pca-service:
    build:
      context: ./pca_service
    container_name: pca-service
    ports:
      - 8600:8600
    networks:
      - agente-net

  multi-cluster-service:
    build:
      context: ./multi_cluster_service
    container_name: multi-cluster-service
    ports:
      - 8700:8700
    networks:
      - agente-net

  cluster-service-pro:
    build:
      context: ./cluster_service_pro     # <- relativo desde C:\AGENTE_IA
    container_name: cluster-service-pro
    ports:
      - 8800:8000
    networks:
      - agente-net

  cluster_interpreter_service:
    build:
      context: ./cluster_interpreter_service
    container_name: cluster_interpreter_service
    ports:
      - 8900:8000
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - agente-net

services:
  cluster_interpreter:
    build:
      context: ./cluster_interpreter
    container_name: cluster_interpreter
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cluster_interpreter:/app
    networks:
      - agente-net


networks:
  agente-net:
    external: true
